#!/usr/bin/env sh

set -xeu

# NOTION_API_KEY="$(kubectl get secret notion-api-key -o=jsonpath='{.data.key}' | base64 -d)"
export NOTION_API_KEY="secret_Cr69ThgW6hSJtwbEpHILoBkCl9FOBTm01HDVn7qZ2kQ"
page_id="$(yq eval '.status.pageDetails.id' /kratix/input/object.yaml)"

curl https://api.notion.com/v1/pages/$page_id \
  -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
  -H "Content-Type: application/json" \
  -H "Notion-Version: 2022-06-28" \
  -X PATCH \
	--data '{
    "archived": true
}'