#!/usr/bin/env sh

set -xeu

NOTION_API_KEY="$(kubectl get secret notion-api-key -o=jsonpath='{.data.key}' | base64 -d)"
page_name="$(yq eval '.spec.name' /kratix/input/object.yaml)"
page_id="$(kubectl get secret notion-api-key -o=jsonpath='{.data.key}' | base64 -d)"

curl 'https://api.notion.com/v1/pages' \
  -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
  -H "Content-Type: application/json" \
  -H "Notion-Version: 2022-06-28" \
  --data '{
  "parent": { "page_id": "'"$page_id"'"},
  "properties": {
		"title": {
      "title": [{ "type": "text", "text": { "content":  "'"$page_name"'" } }]
		}
	}
}' > response.json

id=$(jq -r '.id' response.json)
url=$(jq -r '.url' response.json)

export id
export url

cat /tmp/transfer/notion-document-instance.yaml | yq eval '.spec.name = env(page_name)' > /kratix/output/notion-document-instance.yaml

cat <<EOF > /kratix/metadata/status.yaml
message: Notion page provisioned at url: $url
pageDetails:
  title: ${page_name}
  id: ${id}
  url: ${url}
EOF